sudo: required
language: python
services:
  - docker
python:
  - "3.8"
before_script:
  - docker-compose build
script:
  - docker-compose run --rm web bash -c "flake8 . &&
                                         python wait_for_postgres.py &&
                                         ./manage.py test"

notifications:
  email: false

cache:
  pip: true
