site_name: tabletop_connector_api
site_description: None
repo_url: https://github.com/mborysiak-sp/tabletop-connector
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/mborysiak-sp">mborysiak-sp</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
