# Generated by Django 3.1.2 on 2021-01-08 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_auto_20210106_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='users',
            new_name='participants',
        ),
    ]
