# Generated by Django 3.1.2 on 2020-11-24 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="geo_x",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="address",
            name="geo_y",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="event",
            name="chat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="events.chat",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
