# Generated by Django 3.1.2 on 2020-11-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_auto_20201124_0928"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="geo_x",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="geo_y",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
