# Generated by Django 3.1.2 on 2020-12-13 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20201212_1635'),
        ('events', '0007_auto_20201209_1155'),
    ]

    operations = [
    ]
