# Generated by Django 3.1.2 on 2020-12-13 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0001_initial'),
        ('events', '0008_merge_20201213_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chats.chat'),
        ),
        migrations.AlterField(
            model_name='event',
            name='games',
            field=models.ManyToManyField(related_name='events', to='events.Game'),
        ),
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
