# Generated by Django 3.1.2 on 2020-12-21 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20201218_1720'),
        ('events', '0010_auto_20201217_2132'),
    ]

    operations = [
    ]
