# Generated by Django 3.1.2 on 2020-12-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20201221_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='address',
            name='geo_x',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='address',
            name='geo_y',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
